name: Update ExtractIcon

on:
  push:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:

jobs:
  update-extracticon:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get latest ExtractIcon release
      id: get_release
      uses: actions/github-script@v7
      with:
        script: |
          const { data: releases } = await github.rest.repos.listReleases({
            owner: 'bezalel6',
            repo: 'ExtractIcon',
          });
          
          if (releases.length === 0) {
            throw new Error('No releases found');
          }
          
          const latestRelease = releases[0];
          const exeAsset = latestRelease.assets.find(asset => 
            asset.name.toLowerCase() === 'extracticon.exe'
          );
          
          if (!exeAsset) {
            throw new Error('extracticon.exe not found in latest release');
          }
          
          return {
            download_url: exeAsset.browser_download_url,
            tag_name: latestRelease.tag_name,
            release_name: latestRelease.name
          };
    
    - name: Download ExtractIcon.exe
      run: |
        curl -L -o extracticon.exe "${{ fromJSON(steps.get_release.outputs.result).download_url }}"
        chmod +x extracticon.exe
    
    - name: Check if ExtractIcon.exe changed
      id: check_changes
      run: |
        if git diff --quiet extracticon.exe; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add extracticon.exe
        git commit -m "chore: update extracticon.exe to ${{ fromJSON(steps.get_release.outputs.result).tag_name }}"
        git push