name: Update ExtractIcon

on:
  push:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:

jobs:
  update-extracticon:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download latest ExtractIcon.exe
      run: |
        curl -L -o extracticon.exe https://github.com/bezalel6/ExtractIcon/releases/download/latest/extracticon.exe
        chmod +x extracticon.exe
    
    - name: Check if ExtractIcon.exe changed
      id: check_changes
      run: |
        if git diff --quiet extracticon.exe; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add extracticon.exe
        git commit -m "chore: update extracticon.exe to latest"
        git push